version: '3.5'

services:
  postgres:
    image: postgres:14
    container_name: postgres-prd
    environment:
      POSTGRES_USER: prd
      POSTGRES_PASSWORD: prd
      POSTGRES_DB: prd
    volumes:
      - postgres-prd:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "prd"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - 5432:5432

volumes:
  postgres-prd: