version: '3.5'

services:
  postgres:
    image: postgres:14
    container_name: postgres-dev
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - 5433:5432

volumes:
  postgres-dev: